In [14]:
import numpy as np

marks = np.array([45, 60, 72, 88, 54, 90])

print("Mean:", np.mean(marks))
print("Max:", np.max(marks))
print("Min:", np.min(marks))
print("Pass/Fail:", marks >= 60)
print("Grace Marks:", marks + 5)


Mean: 68.16666666666667
Max: 90
Min: 45
Pass/Fail: [False  True  True  True False  True]
Grace Marks: [50 65 77 93 59 95]


In [15]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])


[[2 3 4]
 [7 8 9]]


In [18]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])


print(arr.shape)

(2, 5)


In [19]:
import numpy as np
arr = np.arange(1, 10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [29]:
data = ["12", "15.5", 20, "AI", None, True, "30"]

clearnumber = [
    int(item)
    for item in data
    if isinstance (item, int) and not isinstance(item, bool)
    or (isinstance(item, str) and item.isdigit())
]

print(clearnumber)
totalnumber = sum(clearnumber)
print(totalnumber / len(clearnumber))

[12, 20, 30]
20.666666666666668
